Feature/agrega script para respaldar volumen
IslasGECI/backup_volumes pull request #1
Opened 2020-12-17 00:00 UTC by MaritzaB

Estas son las funciones que utilizamos para respaldar volumenes del servidor y restaurarlos en caso de pérdida.

2021-01-19 18:37 UTC, nepito requested changes
Listo @MaritzaB, aquí te dejo mi primera revisión :raised_hands:

2021-01-19 18:37 UTC, nepito commented on README.md
> +Para comprobar que el respaldo está en el servidor debes hacer los siguientes pasos:
Por favor completa las instrucciones para poder hacer la verificación en el servidor.

2021-01-19 18:37 UTC, nepito commented on README.md
> +
Por favor revisa que las instrucciones aquí sean correctas.

2021-01-19 18:37 UTC, nepito commented on src/back_up_my_volume
> +  'docker run --rm -v '${source_data_volume_name}':/from alpine ash -c "cd /from ; tar -cf - . "' \
Por favor agrega la versión larga de las instrucciones:
```suggestion
  'docker run --rm --volume '${source_data_volume_name}':/from alpine ash -c "cd /from ; tar --create --file - . "' \
```

2021-01-19 18:37 UTC, nepito commented on src/back_up_my_volume
> +  | docker run --rm -i -v ${target_data_volume_name}:/to alpine ash -c "cd /to ; tar -xpvf - "
Por favor agrega la versión larga de las instrucciones:
```suggestion
  | docker run --rm --interactive --volume ${target_data_volume_name}:/to alpine ash -c "cd /to ; tar --get --preserve-permissions --verbose --file - "
```

2021-01-19 18:37 UTC, nepito commented on src/restore_my_volume
> +docker run --rm -v ${source_data_volume_name}:/from alpine ash -c "cd /from ; tar -cf - . " \
Por favor utiliza la versión larga de las instrucciones

2021-01-19 18:37 UTC, nepito commented on src/restore_my_volume
> +  'docker run --rm -i -v '${target_data_volume_name}':/to alpine ash -c "cd /to ; tar -xpvf - " '
Por favor utiliza la versión larga de las instrucciones

2021-01-19 18:44 UTC, nepito commented
@MaritzaB no pude correr el respaldo hacia el servidor:
![image](https://user-images.githubusercontent.com/35377740/105078683-32694300-5a43-11eb-8a7e-d26fca91b180.png)

2021-01-19 21:28 UTC, MaritzaB commented
Muchas gracias por la revisión @nepito. Efectivamente no estaba corriendo la función `restore_my_volume`, tenía mal una variable de entrada, pero ya quedó 😉 .

2021-01-20 20:03 UTC, nepito requested changes
Ya pude avanzar @MaritzaB. Muchas gracias por atender los comentario.

2021-01-20 20:03 UTC, nepito commented on README.md
> +guardados. Después de hacer un _back up_ deberías de tener un vólumen con el nombre:
Error de dedo:
```suggestion
guardados. Después de hacer un _back up_ deberías de tener un volumen con el nombre:
```

2021-01-20 20:03 UTC, nepito commented on README.md
> +instrucción `./src/restore_my_volume 2021-01-19`.
Para uniformizar el estilo:
```suggestion
instrucción `./src/restore_my_volume fecha` donde en lugar de `fecha` estará la fecha de cuando hiciste el respaldo.
```

2021-01-20 20:03 UTC, nepito commented on README.md
> +
Creo que conviene separar en una tercera sección:
```suggestion

## Verificación del respaldo
```

2021-01-20 20:03 UTC, nepito commented on README.md
> +1. Enlistar los voúmenes de Docker con: `docker volume ls`. El volumen debería de aparecer como
Error de dedo:
```suggestion
1. Enlistar los volúmenes de Docker con: `docker volume ls`. El volumen debería de aparecer como
```

2021-01-20 20:03 UTC, nepito commented on README.md
> +
Podemos agregar un paso más para estar seguros que el volumen que vemos es el que acabamos de subir:
```suggestion
1. Para ver la fecha de creación del volumen utilizamos la instrucción `docker volume inspect siap_mysql_vol`

```

2021-01-22 21:42 UTC, merged

2021-01-22 21:43 UTC, nepito reviewed
Listo @MaritzaB